// Command codegen/query generates the typed Query/Tuple arity ladder for the
// ECS query package (Track M / T-6M01). Go generics have no variadic type
// parameters, so each query arity (Query2, Query3, …) is a distinct generated
// type. The hand-written Query1–Query3 establish the pattern; this tool extends
// the ladder mechanically, emitting code structurally identical to them.
//
// Usage (see the //go:generate directive in internal/ecs/query):
//
//	go run ./cmd/codegen/query -min 4 -max 6 -out internal/ecs/query/query_gen.go
package main

import (
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"strings"
)

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(argv []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("codegen/query", flag.ContinueOnError)
	fs.SetOutput(stderr)
	min := fs.Int("min", 4, "lowest query arity to generate (inclusive)")
	max := fs.Int("max", 6, "highest query arity to generate (inclusive)")
	out := fs.String("out", "", "output file (default: stdout)")
	if err := fs.Parse(argv); err != nil {
		return 2
	}
	if *min < 2 || *max < *min || *max > 26 {
		_, _ = fmt.Fprintf(stderr, "codegen/query: invalid arity range [%d, %d] (want 2 <= min <= max <= 26)\n", *min, *max)
		return 2
	}

	src, err := genSource(*min, *max)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "codegen/query: %v\n", err)
		return 1
	}
	if *out != "" {
		if err := os.WriteFile(*out, src, 0o644); err != nil {
			_, _ = fmt.Fprintf(stderr, "codegen/query: %v\n", err)
			return 2
		}
		return 0
	}
	_, _ = stdout.Write(src)
	return 0
}

// genSource renders the package header plus every arity in [min, max] and
// returns gofmt-formatted source. format.Source doubles as a syntax validator —
// a malformed emission fails here rather than at compile time.
func genSource(min, max int) ([]byte, error) {
	var b strings.Builder
	b.WriteString(`// Code generated by cmd/codegen/query; DO NOT EDIT.

package query

import (
	"iter"

	"github.com/neuengine/neu/internal/ecs/component"
	"github.com/neuengine/neu/internal/ecs/entity"
	"github.com/neuengine/neu/internal/ecs/world"
)
`)
	for n := min; n <= max; n++ {
		b.WriteString(genArity(n))
	}
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

// letter returns the i-th type-parameter letter (0 → "A").
func letter(i int) string { return string(rune('A' + i)) }

// genArity emits the TupleN, QueryN, NewQueryN, State, All, Count, and refresh
// declarations for a single arity n, mirroring the hand-written query2.go.
func genArity(n int) string {
	letters := make([]string, n)
	for i := range letters {
		letters[i] = letter(i)
	}
	params := strings.Join(letters, ", ") // "A, B, C"
	constraint := params + " any"         // "A, B, C any"
	typeArgs := "[" + params + "]"        // "[A, B, C]"

	var b strings.Builder
	p := func(format string, a ...any) { _, _ = fmt.Fprintf(&b, format, a...) }

	// TupleN struct.
	p("\n// Tuple%d is the value yielded by [Query%d.All].\n", n, n)
	p("type Tuple%d[%s] struct {\n", n, constraint)
	for _, l := range letters {
		p("\t%s *%s\n", l, l)
	}
	p("}\n")

	// QueryN struct.
	p("\n// Query%d is a %d-component query yielding (Entity, [Tuple%d]) pairs.\n", n, n, n)
	p("type Query%d[%s] struct {\n", n, constraint)
	p("\tstate    *QueryState\n")
	p("\tperRow   []tickFilterRecord\n")
	p("\tmatched  []world.ArchetypeID\n")
	p("\tnextScan int\n")
	p("\tids      [%d]component.ID\n", n)
	p("}\n")

	// NewQueryN.
	idLocals := make([]string, n)
	for i, l := range letters {
		idLocals[i] = "id" + l
	}
	p("\n// NewQuery%d builds a %d-component query, auto-registering each type as a\n", n, n)
	p("// Table component when first seen. Returns [errSameTypeInQuery] if any two\n")
	p("// type parameters resolve to the same component.\n")
	p("func NewQuery%d[%s](w *world.World, filters ...QueryFilter) (*Query%d%s, error) {\n", n, constraint, n, typeArgs)
	for i, l := range letters {
		p("\t%s := componentIDFor[%s](w)\n", idLocals[i], l)
	}
	p("\tif %s {\n", distinctCond(idLocals))
	p("\t\treturn nil, errSameTypeInQuery\n")
	p("\t}\n")
	p("\tb := applyFilters(w, []component.ID{%s}, filters)\n", strings.Join(idLocals, ", "))
	p("\tstate, err := NewQueryState(b.required, b.excluded, Access{})\n")
	p("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	p("\treturn &Query%d%s{\n", n, typeArgs)
	p("\t\tstate:  state,\n")
	p("\t\tids:    [%d]component.ID{%s},\n", n, strings.Join(idLocals, ", "))
	p("\t\tperRow: b.perRow,\n")
	p("\t}, nil\n")
	p("}\n")

	// State.
	p("\n// State returns the underlying [QueryState].\n")
	p("func (q *Query%d%s) State() *QueryState { return q.state }\n", n, typeArgs)

	// All.
	p("\n// All returns an iterator over every (entity, Tuple%d) pair matching the query.\n", n)
	p("func (q *Query%d%s) All(w *world.World) iter.Seq2[entity.Entity, Tuple%d%s] {\n", n, typeArgs, n, typeArgs)
	p("\tq.refresh(w)\n")
	p("\treturn func(yield func(entity.Entity, Tuple%d%s) bool) {\n", n, typeArgs)
	p("\t\tfor _, archID := range q.matched {\n")
	p("\t\t\tarch := w.Archetypes().At(archID)\n")
	p("\t\t\tentities := arch.Entities()\n")
	p("\t\t\tfor row, e := range entities {\n")
	p("\t\t\t\tif !passesPerRow(w, arch, row, q.perRow) {\n\t\t\t\t\tcontinue\n\t\t\t\t}\n")
	p("\t\t\t\ttup := Tuple%d%s{\n", n, typeArgs)
	for i, l := range letters {
		p("\t\t\t\t\t%s: (*%s)(fetchComponent(w, arch, e, row, q.ids[%d])),\n", l, l, i)
	}
	p("\t\t\t\t}\n")
	p("\t\t\t\tif !yield(e, tup) {\n\t\t\t\t\treturn\n\t\t\t\t}\n")
	p("\t\t\t}\n")
	p("\t\t}\n")
	p("\t}\n")
	p("}\n")

	// Count.
	p("\n// Count returns the number of entities currently matching the query.\n")
	p("func (q *Query%d%s) Count(w *world.World) int {\n", n, typeArgs)
	p("\tq.refresh(w)\n")
	p("\tif len(q.perRow) == 0 {\n")
	p("\t\tn := 0\n")
	p("\t\tfor _, archID := range q.matched {\n\t\t\tn += w.Archetypes().At(archID).Len()\n\t\t}\n")
	p("\t\treturn n\n")
	p("\t}\n")
	p("\tn := 0\n")
	p("\tfor _, archID := range q.matched {\n")
	p("\t\tarch := w.Archetypes().At(archID)\n")
	p("\t\tfor row := 0; row < arch.Len(); row++ {\n")
	p("\t\t\tif passesPerRow(w, arch, row, q.perRow) {\n\t\t\t\tn++\n\t\t\t}\n")
	p("\t\t}\n")
	p("\t}\n")
	p("\treturn n\n")
	p("}\n")

	// refresh.
	p("\nfunc (q *Query%d%s) refresh(w *world.World) {\n", n, typeArgs)
	p("\tstore := w.Archetypes()\n")
	p("\tif q.nextScan == store.Len() {\n\t\treturn\n\t}\n")
	p("\tstore.EachFrom(q.nextScan, func(a *world.Archetype) bool {\n")
	p("\t\tif q.state.MatchesIDs(a.ComponentIDs()) {\n\t\t\tq.matched = append(q.matched, a.ID())\n\t\t}\n")
	p("\t\treturn true\n")
	p("\t})\n")
	p("\tq.nextScan = store.Len()\n")
	p("}\n")

	return b.String()
}

// distinctCond builds the "any two equal" guard, e.g. "idA == idB || idA == idC || idB == idC".
func distinctCond(ids []string) string {
	var pairs []string
	for i := range ids {
		for j := i + 1; j < len(ids); j++ {
			pairs = append(pairs, ids[i]+" == "+ids[j])
		}
	}
	return strings.Join(pairs, " || ")
}
