// Code generated by cmd/codegen/query; DO NOT EDIT.

package query

import (
	"iter"

	"github.com/neuengine/neu/internal/ecs/component"
	"github.com/neuengine/neu/internal/ecs/entity"
	"github.com/neuengine/neu/internal/ecs/world"
)

// Tuple4 is the value yielded by [Query4.All].
type Tuple4[A, B, C, D any] struct {
	A *A
	B *B
	C *C
	D *D
}

// Query4 is a 4-component query yielding (Entity, [Tuple4]) pairs.
type Query4[A, B, C, D any] struct {
	state    *QueryState
	perRow   []tickFilterRecord
	matched  []world.ArchetypeID
	nextScan int
	ids      [4]component.ID
}

// NewQuery4 builds a 4-component query, auto-registering each type as a
// Table component when first seen. Returns [errSameTypeInQuery] if any two
// type parameters resolve to the same component.
func NewQuery4[A, B, C, D any](w *world.World, filters ...QueryFilter) (*Query4[A, B, C, D], error) {
	idA := componentIDFor[A](w)
	idB := componentIDFor[B](w)
	idC := componentIDFor[C](w)
	idD := componentIDFor[D](w)
	if idA == idB || idA == idC || idA == idD || idB == idC || idB == idD || idC == idD {
		return nil, errSameTypeInQuery
	}
	b := applyFilters(w, []component.ID{idA, idB, idC, idD}, filters)
	state, err := NewQueryState(b.required, b.excluded, Access{})
	if err != nil {
		return nil, err
	}
	return &Query4[A, B, C, D]{
		state:  state,
		ids:    [4]component.ID{idA, idB, idC, idD},
		perRow: b.perRow,
	}, nil
}

// State returns the underlying [QueryState].
func (q *Query4[A, B, C, D]) State() *QueryState { return q.state }

// All returns an iterator over every (entity, Tuple4) pair matching the query.
func (q *Query4[A, B, C, D]) All(w *world.World) iter.Seq2[entity.Entity, Tuple4[A, B, C, D]] {
	q.refresh(w)
	return func(yield func(entity.Entity, Tuple4[A, B, C, D]) bool) {
		for _, archID := range q.matched {
			arch := w.Archetypes().At(archID)
			entities := arch.Entities()
			for row, e := range entities {
				if !passesPerRow(w, arch, row, q.perRow) {
					continue
				}
				tup := Tuple4[A, B, C, D]{
					A: (*A)(fetchComponent(w, arch, e, row, q.ids[0])),
					B: (*B)(fetchComponent(w, arch, e, row, q.ids[1])),
					C: (*C)(fetchComponent(w, arch, e, row, q.ids[2])),
					D: (*D)(fetchComponent(w, arch, e, row, q.ids[3])),
				}
				if !yield(e, tup) {
					return
				}
			}
		}
	}
}

// Count returns the number of entities currently matching the query.
func (q *Query4[A, B, C, D]) Count(w *world.World) int {
	q.refresh(w)
	if len(q.perRow) == 0 {
		n := 0
		for _, archID := range q.matched {
			n += w.Archetypes().At(archID).Len()
		}
		return n
	}
	n := 0
	for _, archID := range q.matched {
		arch := w.Archetypes().At(archID)
		for row := 0; row < arch.Len(); row++ {
			if passesPerRow(w, arch, row, q.perRow) {
				n++
			}
		}
	}
	return n
}

func (q *Query4[A, B, C, D]) refresh(w *world.World) {
	store := w.Archetypes()
	if q.nextScan == store.Len() {
		return
	}
	store.EachFrom(q.nextScan, func(a *world.Archetype) bool {
		if q.state.MatchesIDs(a.ComponentIDs()) {
			q.matched = append(q.matched, a.ID())
		}
		return true
	})
	q.nextScan = store.Len()
}

// Tuple5 is the value yielded by [Query5.All].
type Tuple5[A, B, C, D, E any] struct {
	A *A
	B *B
	C *C
	D *D
	E *E
}

// Query5 is a 5-component query yielding (Entity, [Tuple5]) pairs.
type Query5[A, B, C, D, E any] struct {
	state    *QueryState
	perRow   []tickFilterRecord
	matched  []world.ArchetypeID
	nextScan int
	ids      [5]component.ID
}

// NewQuery5 builds a 5-component query, auto-registering each type as a
// Table component when first seen. Returns [errSameTypeInQuery] if any two
// type parameters resolve to the same component.
func NewQuery5[A, B, C, D, E any](w *world.World, filters ...QueryFilter) (*Query5[A, B, C, D, E], error) {
	idA := componentIDFor[A](w)
	idB := componentIDFor[B](w)
	idC := componentIDFor[C](w)
	idD := componentIDFor[D](w)
	idE := componentIDFor[E](w)
	if idA == idB || idA == idC || idA == idD || idA == idE || idB == idC || idB == idD || idB == idE || idC == idD || idC == idE || idD == idE {
		return nil, errSameTypeInQuery
	}
	b := applyFilters(w, []component.ID{idA, idB, idC, idD, idE}, filters)
	state, err := NewQueryState(b.required, b.excluded, Access{})
	if err != nil {
		return nil, err
	}
	return &Query5[A, B, C, D, E]{
		state:  state,
		ids:    [5]component.ID{idA, idB, idC, idD, idE},
		perRow: b.perRow,
	}, nil
}

// State returns the underlying [QueryState].
func (q *Query5[A, B, C, D, E]) State() *QueryState { return q.state }

// All returns an iterator over every (entity, Tuple5) pair matching the query.
func (q *Query5[A, B, C, D, E]) All(w *world.World) iter.Seq2[entity.Entity, Tuple5[A, B, C, D, E]] {
	q.refresh(w)
	return func(yield func(entity.Entity, Tuple5[A, B, C, D, E]) bool) {
		for _, archID := range q.matched {
			arch := w.Archetypes().At(archID)
			entities := arch.Entities()
			for row, e := range entities {
				if !passesPerRow(w, arch, row, q.perRow) {
					continue
				}
				tup := Tuple5[A, B, C, D, E]{
					A: (*A)(fetchComponent(w, arch, e, row, q.ids[0])),
					B: (*B)(fetchComponent(w, arch, e, row, q.ids[1])),
					C: (*C)(fetchComponent(w, arch, e, row, q.ids[2])),
					D: (*D)(fetchComponent(w, arch, e, row, q.ids[3])),
					E: (*E)(fetchComponent(w, arch, e, row, q.ids[4])),
				}
				if !yield(e, tup) {
					return
				}
			}
		}
	}
}

// Count returns the number of entities currently matching the query.
func (q *Query5[A, B, C, D, E]) Count(w *world.World) int {
	q.refresh(w)
	if len(q.perRow) == 0 {
		n := 0
		for _, archID := range q.matched {
			n += w.Archetypes().At(archID).Len()
		}
		return n
	}
	n := 0
	for _, archID := range q.matched {
		arch := w.Archetypes().At(archID)
		for row := 0; row < arch.Len(); row++ {
			if passesPerRow(w, arch, row, q.perRow) {
				n++
			}
		}
	}
	return n
}

func (q *Query5[A, B, C, D, E]) refresh(w *world.World) {
	store := w.Archetypes()
	if q.nextScan == store.Len() {
		return
	}
	store.EachFrom(q.nextScan, func(a *world.Archetype) bool {
		if q.state.MatchesIDs(a.ComponentIDs()) {
			q.matched = append(q.matched, a.ID())
		}
		return true
	})
	q.nextScan = store.Len()
}

// Tuple6 is the value yielded by [Query6.All].
type Tuple6[A, B, C, D, E, F any] struct {
	A *A
	B *B
	C *C
	D *D
	E *E
	F *F
}

// Query6 is a 6-component query yielding (Entity, [Tuple6]) pairs.
type Query6[A, B, C, D, E, F any] struct {
	state    *QueryState
	perRow   []tickFilterRecord
	matched  []world.ArchetypeID
	nextScan int
	ids      [6]component.ID
}

// NewQuery6 builds a 6-component query, auto-registering each type as a
// Table component when first seen. Returns [errSameTypeInQuery] if any two
// type parameters resolve to the same component.
func NewQuery6[A, B, C, D, E, F any](w *world.World, filters ...QueryFilter) (*Query6[A, B, C, D, E, F], error) {
	idA := componentIDFor[A](w)
	idB := componentIDFor[B](w)
	idC := componentIDFor[C](w)
	idD := componentIDFor[D](w)
	idE := componentIDFor[E](w)
	idF := componentIDFor[F](w)
	if idA == idB || idA == idC || idA == idD || idA == idE || idA == idF || idB == idC || idB == idD || idB == idE || idB == idF || idC == idD || idC == idE || idC == idF || idD == idE || idD == idF || idE == idF {
		return nil, errSameTypeInQuery
	}
	b := applyFilters(w, []component.ID{idA, idB, idC, idD, idE, idF}, filters)
	state, err := NewQueryState(b.required, b.excluded, Access{})
	if err != nil {
		return nil, err
	}
	return &Query6[A, B, C, D, E, F]{
		state:  state,
		ids:    [6]component.ID{idA, idB, idC, idD, idE, idF},
		perRow: b.perRow,
	}, nil
}

// State returns the underlying [QueryState].
func (q *Query6[A, B, C, D, E, F]) State() *QueryState { return q.state }

// All returns an iterator over every (entity, Tuple6) pair matching the query.
func (q *Query6[A, B, C, D, E, F]) All(w *world.World) iter.Seq2[entity.Entity, Tuple6[A, B, C, D, E, F]] {
	q.refresh(w)
	return func(yield func(entity.Entity, Tuple6[A, B, C, D, E, F]) bool) {
		for _, archID := range q.matched {
			arch := w.Archetypes().At(archID)
			entities := arch.Entities()
			for row, e := range entities {
				if !passesPerRow(w, arch, row, q.perRow) {
					continue
				}
				tup := Tuple6[A, B, C, D, E, F]{
					A: (*A)(fetchComponent(w, arch, e, row, q.ids[0])),
					B: (*B)(fetchComponent(w, arch, e, row, q.ids[1])),
					C: (*C)(fetchComponent(w, arch, e, row, q.ids[2])),
					D: (*D)(fetchComponent(w, arch, e, row, q.ids[3])),
					E: (*E)(fetchComponent(w, arch, e, row, q.ids[4])),
					F: (*F)(fetchComponent(w, arch, e, row, q.ids[5])),
				}
				if !yield(e, tup) {
					return
				}
			}
		}
	}
}

// Count returns the number of entities currently matching the query.
func (q *Query6[A, B, C, D, E, F]) Count(w *world.World) int {
	q.refresh(w)
	if len(q.perRow) == 0 {
		n := 0
		for _, archID := range q.matched {
			n += w.Archetypes().At(archID).Len()
		}
		return n
	}
	n := 0
	for _, archID := range q.matched {
		arch := w.Archetypes().At(archID)
		for row := 0; row < arch.Len(); row++ {
			if passesPerRow(w, arch, row, q.perRow) {
				n++
			}
		}
	}
	return n
}

func (q *Query6[A, B, C, D, E, F]) refresh(w *world.World) {
	store := w.Archetypes()
	if q.nextScan == store.Len() {
		return
	}
	store.EachFrom(q.nextScan, func(a *world.Archetype) bool {
		if q.state.MatchesIDs(a.ComponentIDs()) {
			q.matched = append(q.matched, a.ID())
		}
		return true
	})
	q.nextScan = store.Len()
}
